### ISSUE TITLE
improper argument at TEST_F(ReadOnlySessionTest, WrapInvalid)

### ISSUE THREAD

**Issue by civanahmetyasin** [google/pkcs11test#37]
https://github.com/google/pkcs11test/blob/df70f7172c8853e7074e6636acdcdb13b5da5272/key.cc#L193
Why do you use here `pWrappedKey` as `NULL_PTR` ?
Why didn't you use `data`?
Is this a mistake?

**Comment by daviddrysdale** [comment]
This is deliberate, as ~~explained~~ hinted at by the comment before:
```c++
  // Too-small output cases.
  EXPECT_CKR_OK(g_fns->C_WrapKey(session_, &wrap_mechanism, k2.handle(), k1.handle(), NULL_PTR, &data_len));
  data_len = 1;
  EXPECT_CKR(CKR_BUFFER_TOO_SMALL,
             g_fns->C_WrapKey(session_, &wrap_mechanism, k2.handle(), k1.handle(), data, &data_len));
```

The final two parameters for `C_WrapKey` are a pointer and a length for memory that will receive the wrapped key. This test checks what happens if either of those two parameters is wrong &ndash; either a `nullptr` or a tiny length, to check that the PKCS#11 implementation is validating those parameters.

(This is all assuming I recall correctly &ndash; it's from a while ago).
